### ISSUE TITLE
Auto-open upload website

### ISSUE THREAD

**Issue by quantum9Innovation** [Quantalabs/pastebin#1]
Pastebin should automatically open the uploader website instead of simply displaying it in the command line and hoping that the user's terminal will identify the hyperlink (many terminals, such as the built-in Node.js one, do not do this and this can be very annoying for the user). When this is done, Pastebin should mirror other JavaScript projects like Charts.js that have similar auto-open magic bundled with them.

**Comment by Quantalabs** [comment]
Fixed in cd1826a1b1b9dd5f6df538264af49ae83079fd55
