### ISSUE TITLE
Create uploader textarea

### ISSUE THREAD

**Issue by quantum9Innovation** [Quantalabs/pastebin#2]
While files are necessary for transporting certain types of data (e.g. images), they can be an unnecessary hassle for transporting simpler data like URLs, which can be transported as plain text. Rather than creating a `.txt` file for no reason, Pastebin could simplify this process by creating an 'annotation' or 'comment' `<textarea>` on the uploader website that would allow users to paste-in content. This content could then be displayed on the downloader website and be copied to clipboard automatically.

**Comment by Quantalabs** [comment]
Fixed in a426e060b3df8f3837375fc95f609f7a5998cd55

**Comment by quantum9Innovation** [comment]
@Quantalabs reopen this as the way the feature is currently being implemented is insufficient.
1) The `<textarea>` should have a centered appearance and autoscale according to its content to fit into the UI on the screen
2) There should be a clear QR indicator directing the user to the website to copy the pasted content and a "copy" button that copies that content onto that device's clipboard
